### ISSUE TITLE
Proclub HA Submission 

### ISSUE THREAD

**Issue by 2pai** [2pai/kiana#1]
This project addressed to helloproclub/tenjin#4 for Proclub HA Submission

**Comment by BlinfoldKing** [comment]
ini mau pake es berapa btw es6?

**Comment by BlinfoldKing** [comment]
aea541efd71a4829ac3d7ab8baacde9a7a64497f

commented, btw pasang logger juga biar gampang debug:
https://github.com/pinojs/pino

mau pake logger yanglain juga boleh

**Comment by 2pai** [comment]
> ini mau pake es berapa btw es6?

CommonJS sih mas @BlinfoldKing 

> [aea541e](https://github.com/2pai/kiana/commit/aea541efd71a4829ac3d7ab8baacde9a7a64497f)
> 
> commented, btw pasang logger juga biar gampang debug:
> https://github.com/pinojs/pino
> https://github.com/pinojs/express-pino-logger
> 
> mau pake logger yanglain juga boleh

baik mas

**Comment by 2pai** [comment]
Paling loggernya pake winston mas

**Comment by BlinfoldKing** [comment]
oce siyap

**Comment by jeremylombogia** [comment]
Good, image docker nya yang lengkap ya ntar..

**Comment by 2pai** [comment]
Oke noted @jeremylombogia
